# Generated by Django 3.1.3 on 2021-05-28 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assuntos',
            fields=[
                ('codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=250)),
                ('cod_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='assuntos_pai', to='geo.assuntos')),
            ],
            options={
                'verbose_name': 'Assuto',
                'verbose_name_plural': 'Assuntos',
            },
        ),
    ]
