# Generated by Django 3.1.3 on 2021-05-28 18:00

from django.db import migrations, models
import geo.models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('processo', models.CharField(blank=True, max_length=255)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to=geo.models.user_directory_path)),
                ('cod_sigef', models.CharField(blank=True, max_length=50, null=True)),
                ('terrai_cod', models.CharField(blank=True, max_length=50, null=True)),
                ('cod_floresta', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='municipio',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
