# Generated by Django 3.1.3 on 2021-05-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20210528_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='processo',
            new_name='numero',
        ),
    ]
