# Generated by Django 3.1.3 on 2021-05-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_auto_20210528_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='cod_municipio_ibge',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
