# Generated by Django 3.1.3 on 2021-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_processo_sicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='sirenejud',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
