# Generated by Django 3.1.3 on 2021-05-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_auto_20210529_0758'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataJud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=255)),
                ('sirenejud', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('latitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('cod_sigef', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sicar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sicar', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('datajud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.datajud')),
            ],
        ),
    ]
