# Generated by Django 3.1.3 on 2021-05-30 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_datajud_sicar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datajud',
            options={'verbose_name': 'DataJud', 'verbose_name_plural': 'DataJud'},
        ),
    ]
