# Generated by Django 3.1.3 on 2021-05-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20210529_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='id',
        ),
        migrations.AlterField(
            model_name='processo',
            name='numero',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
